# X11 Touchpad Configuration

Section "InputClass"
Identifier "system-touchpad"
MatchIsTouchpad "on"

# Disable acceleration
Option "AccelProfile" "flat"

# Tap to click and natural scrolling
Option "Tapping" "on"
Option "NaturalScrolling" "true"
EndSection
